# Generated by Django 2.2 on 2020-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_auto_20200323_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_publihed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации '),
        ),
    ]
