# Generated by Django 2.2 on 2020-03-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_date_publihed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('DR', 'Черновик'), ('PR', 'Проверка'), ('PU', 'Обубликовано')], default='DR', max_length=2),
        ),
    ]
