# Generated by Django 2.2 on 2020-03-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_auto_20200323_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleapp.Article')),
            ],
        ),
    ]
